# ==========================================
# APPLICATION CONFIGURATION
# ==========================================

spring.application.name=student-course-registration


# ==========================================
# SERVER CONFIGURATION
# ==========================================

server.port=8081


# ==========================================
# ERROR CONFIGURATION
# ==========================================

server.error.include-message=never
server.error.include-binding-errors=never